version: 1
cgroup-root: AUTO # path to cgroupfs v2 mount point or "AUTO"
marks: '[3000,3100)' # fwmark range for identify tproxy target

tproxies:
  clash:
    port: 7893
    addr: 127.0.0.1 # ignored for now
    dns-hijack:
      addr: 127.0.0.1
      port: 53

rules:
  - match: \/system\.slice\/clash-meta\.service
    direct: true
  - match: \/user\.slice\/user-\d+\.slice/user@\d+\.service\/cgtproxy-direct\.slice\/.*
    direct: true
  - match: \/.*
    tproxy: clash

bypass:
  ipv4:
    - 127.0.0.1
