version: 1
cgroup-root: AUTO
marks: '[3000,3100)'

tproxies:
  clash:
    port: 7893
    addr: 127.0.0.1

rules:
  - match: \/user\.slice\/user-\d+\.slice/user@\d+\.service\/app\.slice\/.*
    tproxy: clash

bypass:
  ipv4:
    - 127.0.0.1
