version: 1
cgroup-root: AUTO # path to cgroupfs v2 mount point or "AUTO"
marks: '[3000,3100)' # fwmark range for identify tproxy target

tproxies:
  clash:
    port: 7893
    addr: 127.0.0.1 # ignored for now
    # no-udp: false
    # no-ipv6: false
    # mark: 4000 # you can set mark for each tproxies

rules:
  - match: \/system\.slice\/system-clash\d+\.slice/.*
    direct: true
  - match: \/user\.slice\/user-\d+\.slice/user@\d+\.service\/direct\.slice\/.*
    direct: true
  - match: \/.*
    tproxy: clash
    # drop: true
    # direct: true

bypass:
  ipv4:
    - 127.0.0.1
