version: 1
cgroup-root: AUTO
rules:
  - match: /user.slice/user-1000.slice/user@1000.service/app.slice/*
    proxy:
      udp: true
      port: 1080
      protocol: socks
      addr: 127.0.0.1
repeater:
  listens:
    - 127.0.0.1
  tproxy-ports: "[13030,13040)"
